<?php

return [
    'NEWS_API_AUTH_KEY' => env('NEWS_API_AUTH_KEY'),
    'NEWYORK_TIMES_API_AUTH_KEY' => env('NEWYORK_TIMES_API_AUTH_KEY'),
    'THE_GUARDIAN_API_AUTH_KEY' => env('THE_GUARDIAN_API_AUTH_KEY')
];