version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_DATABASE: 'innoscripta'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
      DB_PORT: 3306
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mysql
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
        - 3306:3306
    environment:
      MYSQL_DATABASE: 'innoscripta'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - .dbdata:/var/lib/mysql/
    networks:
      - app

networks:
  app:
    driver: bridge